-- AlterTable
ALTER TABLE `hotels_comments` MODIFY `date` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0);

-- AlterTable
ALTER TABLE `houses_comments` MODIFY `date` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0);
